# Array Manipulation Routines

In [1]:
import numpy as np
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

### Reshape

In [2]:
y= x.reshape( (3,2) )
y

array([[0, 1],
       [2, 3],
       [4, 5]])

In [3]:
x = np.array( [[0,1,2],[3,4,5] ], dtype=np.uint8)
x

array([[0, 1, 2],
       [3, 4, 5]], dtype=uint8)

In [4]:
y = np.reshape(x,6)
y

array([0, 1, 2, 3, 4, 5], dtype=uint8)

### Flatten

In [5]:
y = np.ravel(x) # flattern
y

array([0, 1, 2, 3, 4, 5], dtype=uint8)

In [6]:
x

array([[0, 1, 2],
       [3, 4, 5]], dtype=uint8)

In [8]:
y = x.flatten()
y

array([0, 1, 2, 3, 4, 5], dtype=uint8)

In [10]:
y = x.flatten('C') # by column (default)
y

array([0, 1, 2, 3, 4, 5], dtype=uint8)

In [11]:
y = x.flatten('F') # by row
y

array([0, 3, 1, 4, 2, 5], dtype=uint8)

.flatten(order): {‘C’, ‘F’, ‘A’, ‘K’}, optional
‘C’ means to flatten in row-major (C-style) order. ‘F’ means to flatten in column-major (Fortran- style) order. ‘A’ means to flatten in column-major order if a is Fortran contiguous in memory, row-major order otherwise. ‘K’ means to flatten a in the order the elements occur in memory. The default is ‘C’.

### Stack

In [13]:
x = np.array( [1,2,3], dtype=np.uint8)
y = np.array( [4,5,6], dtype=np.uint8)
print(x.dtype)
print(x)
print(y)

uint8
[1 2 3]
[4 5 6]


In [14]:
z = np.stack( [x,y])
z

array([[1, 2, 3],
       [4, 5, 6]], dtype=uint8)

In [15]:
z = np.stack ( [x,y], axis=0)
z

array([[1, 2, 3],
       [4, 5, 6]], dtype=uint8)

In [16]:
z = np.stack ( [x,y], axis=-1)
z

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=uint8)

In [21]:
np.stack ( [x,y], axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=uint8)

In [22]:
(x,y)

(array([1, 2, 3], dtype=uint8), array([4, 5, 6], dtype=uint8))

In [23]:
np.dstack((x,y))

array([[[1, 4],
        [2, 5],
        [3, 6]]], dtype=uint8)

In [56]:
np.dstack( [[1,2,3,4],[5,6,7,8]])

array([[[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]]])

In [57]:
np.dstack((x,y)).shape

(4, 4, 6)

In [25]:
np.hstack((x,y))

array([1, 2, 3, 4, 5, 6], dtype=uint8)

In [26]:
np.vstack((x,y))

array([[1, 2, 3],
       [4, 5, 6]], dtype=uint8)

In [27]:
np.vstack((x,y)).shape

(2, 3)

In [28]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### Split

In [29]:
a,b,c= np.split(x,3)
a,b,c

(array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]))

In [33]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [46]:
x = np.array( [ np.split(x,4) for x in np.split(np.arange(4*4*4),4)])
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [52]:
y,z=np.split(x, 2)
y, z

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]],
 
        [[16, 17, 18, 19],
         [20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31]]]), array([[[32, 33, 34, 35],
         [36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]],
 
        [[48, 49, 50, 51],
         [52, 53, 54, 55],
         [56, 57, 58, 59],
         [60, 61, 62, 63]]]))

In [63]:
print(x)
print('-'*20)
y,z=np.dsplit(x, 2) # along the 3rd axis (depth). Cut center of [0 1 2 3]
print(y)
print(z)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]]
--------------------
[[[ 0  1]
  [ 4  5]
  [ 8  9]
  [12 13]]

 [[16 17]
  [20 21]
  [24 25]
  [28 29]]

 [[32 33]
  [36 37]
  [40 41]
  [44 45]]

 [[48 49]
  [52 53]
  [56 57]
  [60 61]]]
[[[ 2  3]
  [ 6  7]
  [10 11]
  [14 15]]

 [[18 19]
  [22 23]
  [26 27]
  [30 31]]

 [[34 35]
  [38 39]
  [42 43]
  [46 47]]

 [[50 51]
  [54 55]
  [58 59]
  [62 63]]]


In [62]:
print(x)
print('-'*20)
y,z=np.hsplit(x, 2) # 
print(y)
print(z)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]]
--------------------
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[32 33 34 35]
  [36 37 38 39]]

 [[48 49 50 51]
  [52 53 54 55]]]
[[[ 8  9 10 11]
  [12 13 14 15]]

 [[24 25 26 27]
  [28 29 30 31]]

 [[40 41 42 43]
  [44 45 46 47]]

 [[56 57 58 59]
  [60 61 62 63]]]


In [64]:
print(x)
print('-'*20)
y,z=np.vsplit(x, 2) # 
print(y)
print(z)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]]
--------------------
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]
[[[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]]


### Flip

In [65]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [66]:
y = np.flip( x, axis=-1)
y

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12]])

In [67]:
y = np.flip( x, axis=0)
y

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [68]:
y = np.flip( x, axis=1)
y

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12]])

In [69]:
y = np.fliplr( x) # flip left to right
y

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12]])

In [70]:
y = np.flipud( x) # flip up to down
(x,y)

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]), array([[12, 13, 14, 15],
        [ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]]))

### Roll

In [73]:
y = np.roll(x,1)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[15  0  1  2]
 [ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


### Rot90

In [74]:
y = np.rot90(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]
 [ 0  4  8 12]]
