In [33]:
import numpy as np
x0 = np.array( [0,1,0,1], np.uint8 )
y0 = np.array( [0,0,1,1], np.uint8 )

print( np.bitwise_and(x0,y0) )

[0 0 0 1]


In [36]:
print( np.bitwise_and(x0,y0) )
print( np.bitwise_or(x0,y0) )
print( np.bitwise_xor(x0,y0) )
print( np.bitwise_not(x0)  ) # binary compensation of a 8bit number

[0 0 0 1]
[0 1 1 1]
[0 1 1 0]
[255 254 255 254]
