In [4]:
import numpy as np
x= np.random.randint( low=0, high=9, size=10 )
x

array([6, 0, 6, 6, 1, 5, 5, 2, 1, 6])

In [7]:
x = np.random.rand(3,3)
x

array([[0.7926611 , 0.38406805, 0.73992172],
       [0.60188061, 0.08646932, 0.02224685],
       [0.07585437, 0.89734901, 0.46779976]])

In [8]:
x = np.random.rand(2,2,2,2)
x

array([[[[0.67363247, 0.79821253],
         [0.47528904, 0.51190203]],

        [[0.54714765, 0.93311047],
         [0.88318496, 0.77947922]]],


       [[[0.28817482, 0.56068959],
         [0.27297324, 0.52890439]],

        [[0.89430677, 0.2333299 ],
         [0.39528741, 0.59937139]]]])